### ISSUE TITLE
Unable to convert to VS 2017 project format

### ISSUE THREAD

**Issue by rasjidw** [OctopusDeploy/Octodiff#11]
Attempting to open the project in VS 2017 community edition gives errors.

Octodiff\Octodiff.xproj: Failed to migrate XProj project Octodiff. 'dotnet migrate --skip-backup -s -x "...\Octodiff\source\Octodiff\Octodiff.xproj" "...\Octodiff\source\Octodiff\project.json" -r "...\AppData\Local\Temp\gup2fn3o.mk3" --format-report-file-json' exited with error code 1.

Octodiff\Octodiff.xproj: Migration failed. System.ArgumentNullException: Value cannot be null. Parameter name: version at NuGet.Versioning.VersionRangeBase.Satisfies(NuGetVersion version, IVersionComparer comparer) at NuGet.Versioning.VersionRangeBase.Satisfies(NuGetVersion version) at Microsoft.DotNet.ProjectJsonMigration.Rules.MigratePackageDependenciesAndToolsRule.<>c__DisplayClass11_0.<ToPackageDependencyInfo>b__2(VersionRange p) at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found) at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate) at Microsoft.DotNet.ProjectJsonMigration.Rules.MigratePackageDependenciesAndToolsRule.ToPackageDependencyInfo(ProjectLibraryDependency dependency, IDictionary`2 dependencyToVersionMap) at Microsoft.DotNet.ProjectJsonMigration.Rules.MigratePackageDependenciesAndToolsRule.MigrateDependencies(Project project, MigrationRuleInputs migrationRuleInputs, NuGetFramework framework, IEnumerable`1 dependencies, SlnFile solutionFile, ProjectItemGroupElement itemGroup) at Microsoft.DotNet.ProjectJsonMigration.Rules.MigratePackageDependenciesAndToolsRule.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs) at Microsoft.DotNet.ProjectJsonMigration.DefaultMigrationRuleSet.Apply(MigrationSettings migrationSettings, MigrationRuleInputs migrationRuleInputs) at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.MigrateProject(MigrationSettings migrationSettings) at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences) at Microsoft.DotNet.Tools.MigrateCommand.MigrateCommand.Execute() at Microsoft.DotNet.Tools.Migrate.MigrateCommandCompose.Run(String[] args) at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient) at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by alfhenrik** [comment]
Hi @rasjidw,

The reason you are seeing this error is because we're referencing package and assembly version with `*` and this is not valid.

I'll get the code up to VS2017 as soon as possible.

Thank you,
Henrik
