### ISSUE TITLE
Unable to load the project in Visual Studio 2017

### ISSUE THREAD

**Issue by Nirmalya-Kundu** [OctopusDeploy/Octodiff#13]
Hi While I am trying to load the project by  sln file in Visual Studio 2017 but I am unable to do so  as the projects are not loading .

Please help me with a version which will get loaded in visual studio

**Comment by alfhenrik** [comment]
Hi @Nirmalya-Kundu,
We're currently working on fixing this in https://github.com/OctopusDeploy/Octodiff/pull/12

Thanks,
Henrik

**Comment by Nirmalya-Kundu** [comment]
Hi 

Thanks for your response. Please notify me after the VS 2017 version is ready.   

Can You please tell how to run this project for now? Is there any documentation available which I will follow  run the project for now. as I want to test the sync 

Regards
Nirmalya

**Comment by alfhenrik** [comment]
Either you can grab the code from the `vs2017csproj` branch, or download the package from https://github.com/OctopusDeploy/Octodiff/releases/tag/v1.1.2 and use `Octodiff.exe` from `lib/net40`.

**Comment by Nirmalya-Kundu** [comment]
Hi 

There is no package folder Under https://github.com/OctopusDeploy/Octodiff/releases/tag/v1.1.2  so I am not getting lib/net40 and The meaning of vs2017csproj branch is not clear to me also

**Comment by alfhenrik** [comment]
@Nirmalya-Kundu Download the NuGet package https://github.com/OctopusDeploy/Octodiff/releases/download/v1.1.2/Octodiff.1.1.2.nupkg, then extract it (rename to `.zip` instead of `.nupkg` and extract the zip file).

Thanks,
Henrik

**Comment by Nirmalya-Kundu** [comment]
Hi 

Thanks for your help and guidance. Its working now.

**Comment by Nirmalya-Kundu** [comment]
I have one more question, I have noticed one thing that is if I using a complex( a png file of 1 mb or a jpg file) file the patching is not working properly. I mean to say that its not creating the new file.

Can You please tell me why is this happening.
 If you want I will share you the delta, signature and the image files
