### ISSUE TITLE
When Syncing a complex file(Image) Causing Problem

### ISSUE THREAD

**Issue by Nirmalya-Kundu** [OctopusDeploy/Octodiff#14]
I have one more question, I have noticed one thing that is if I using a complex( a png file of 1 mb or a jpg file) file the patching is not working properly. I mean to say that its not creating the new file.

Can You please tell me why is this happening.
If you want I will share you the delta, signature and the image files so that we will able to overcome the issue and make the thing perfect

Hope to hear back from you soon

**Comment by tothegills** [comment]
Hi @Nirmalya-Kundu,

If you wouldn't mind sharing the files that would be excellent.  Note that sharing them here will make the files public.
