### ISSUE TITLE
Class SignatureWriter is not public

### ISSUE THREAD

**Issue by mcollera** [OctopusDeploy/Octodiff#15]
When trying to reference the dll in my code I am unable to access the SignatureWriter class. Can we please get this class set as public in file ISignatureWriter.cs

I appreciate the support.

**Comment by alfhenrik** [comment]
Hi @mcollera,

This is now available on NuGet in version `1.2.1` (might be a little while before it pops up as the NuGet indexing takes a little while).

Cheers,
Henrik
