### ISSUE TITLE
rdiff compatibility?

### ISSUE THREAD

**Issue by maxlinc** [OctopusDeploy/Octodiff#3]
The README says:

> inspired by rdiff, and like rdiff the algorithm is based on rsync

I was curious if I'd be able to sync files between rdiff (on *nix systems) and Octodiff on Windows. I tried it out and noticed there is definitely a superficial incompatibility - they use different magic numbers - but I wasn't sure if there was a deeper incompatibility.

Other than the magic numbers are there any major differences between octodiff and rdiff files? Do you think rdiff compatibility is possible in the future?

**Comment by PaulStovell** [comment]
Octodiff uses the same algorithm/approach, but the file types it generates were made up without looking at the file format that rdiff uses. So unfortunately there is no way to generate a signature or delta with Octodiff and do something with it in rdiff, or vice-versa.
