### ISSUE TITLE
Is this extra code?

### ISSUE THREAD

**Issue by MartinDWhite** [OctopusDeploy/Octodiff#6]
Line 52 in SignatureBuilder.cs in WriteMetadata(Stream stream, ISignatureWriter signatureWriter)
...
var hash = HashAlgorithm.ComputeHash(stream);
...

This line does not appear to have any effect. hash as passed to WriteMetaData, is not used. Removal of this line does not effect the resulting signature file/delta/patch files or the resulting patched files in my testing. This seems to calculate a value (that takes a very long time on large files) and then throw that value away. What is the purpose of this line?

**Comment by droyad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OctoDiff - Is this extra code? #6](https://trello.com/c/mpwJPNwL/105-octodiff-is-this-extra-code-6)

**Comment by MartinDWhite** [comment]
droyad - That link goes to a page I don't have access to see.

**Comment by markryd** [comment]
Thanks for letting us know about this @MartinDWhite. Really sorry it has taken us so long to look into it.
